name: AiNiee Beta Build.
on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  push:
    branches:
      - main

# Add permissions needed for release management
permissions:
  contents: write    # Required for creating/deleting releases, tags, and generating release notes

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        # Fetch depth 0 is needed for generate_release_notes to find previous tags/commits
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for all branches and tags


      # 可以减少可执行文件体积
      - name: Install UPX
        shell: cmd
        run: |
          choco install upx -y

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          python -m pip install -r requirements.txt
          python -m pip install --no-deps -r requirements_no_deps.txt
          python -m pip cache purge

      - name: Build EXE
        run: python .\Tools\pyinstall.py

      - name: Pack Resource
        run: |
          Copy-Item -Path "Resource" -Destination "dist\Resource" -Recurse -Force
          Copy-Item -Path "StevExtraction" -Destination "dist\StevExtraction" -Recurse -Force
          Copy-Item -Path "PluginScripts" -Destination "dist\PluginScripts" -Recurse -Force
          Compress-Archive -Path "dist" -DestinationPath "AiNiee-Beta.zip"

      - name: Delete release
        uses: dev-drprasad/delete-tag-and-release@v1.1 
        with:
          tag_name: Beta
          delete_release: true
          github_token: ${{ secrets.AINIEE }}
        continue-on-error: true

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Beta
          name: AiNiee-Beta 开发测试版本，由最新源码自动打包 
          draft: false
          prerelease: true
          generate_release_notes: true 
          files: AiNiee-Beta.zip
          token: ${{ secrets.AINIEE }}