name: AiNiee-chatgpt Action monitors the main branch commit and automatically packs it into an exe file to Beta release.
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller openai cohere anthropic numpy openpyxl PyQt5 "PyQt-Fluent-Widgets[full]" opencc tiktoken google-generativeai ebooklib beautifulsoup4 pandas chardet PyYAML 

      - name: Modify opencc
        run: |
          (Get-Command python).Path | ForEach-Object { $_ -replace 'python\.exe$', 'Lib\site-packages\opencc\__init__.py' } | ForEach-Object { $content = Get-Content $_; $content -replace '_thisdir = .+', '_thisdir = os.path.dirname(os.path.abspath(sys.argv[0]))' | Set-Content $_ }

      - name: Build EXE
        run: pyinstaller -F -i ./resource/Avatar.png ./AiNiee4.py

      - name: Zip dist folder
        run: |
          $openccPath = (Get-Command python).Path | ForEach-Object { $_ -replace 'python\.exe$', 'Lib\site-packages\opencc' }
          $clibPath = Join-Path -Path $openccPath -ChildPath 'clib'
          Copy-Item -Path "$clibPath" -Destination "dist\clib" -Recurse -Force
          Copy-Item -Path "resource" -Destination "dist\resource" -Recurse -Force
          Copy-Item -Path "StevExtraction" -Destination "dist\StevExtraction" -Recurse -Force
          Copy-Item -Path "SakuraLLMScript" -Destination "dist\SakuraLLMScript" -Recurse -Force
          Compress-Archive -Path "dist" -DestinationPath "AiNiee-Beta.zip"
          
      - name: Delete release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          tag_name: Beta
          delete_release: true
        env:
          GITHUB_TOKEN: ${{ secrets.AINIEE }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.AINIEE }}
        with:
          tag_name: Beta
          release_name: AiNiee测试版 自动同步源码
          draft: false
          prerelease: true

      - name: Upload file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.AINIEE }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./AiNiee-Beta.zip
          asset_name: AiNiee-Beta.zip
          asset_content_type: application/octet-stream
